[versions]
activityKtx = "1.9.1"
agp = "8.4.0"
credentialsPlayServicesAuth = "1.2.0-rc1"
kotlin = "1.9.23"
coreKtx = "1.13.1"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
lifecycleRuntimeKtx = "2.8.2"
activityCompose = "1.9.0"
composeBom = "2023.08.00"
appcompat = "1.7.0"
material = "1.12.0"
ksp = "1.9.23-1.0.20"
androidTools = "31.4.1"
navigation = "2.8.0-beta02"
javaxInject = "1"
desugaring = "2.0.4"
hilt = "2.51.1"
hiltNavigation = "1.2.0"
gmsPlugin = "4.4.0"
kotlinxCoroutines = "1.8.1"
androidxComposeCompiler = "1.5.11"
firebaseBom = "33.1.0"
retrofit = "2.9.0"
okhttp = "4.12.0"
serialization = "1.6.3"
glide = "1.0.0-beta01"
calendar = "2.6.0-beta01"
googleid = "1.1.1"
jsoup = "1.18.1"
webkit = "1.11.0"
material3 = "1.2.1"
playServicesAuth = "21.2.0"
playServicesCoroutines = "1.6.4"
androidxDataStore = "1.1.1"
coreSplashscreen = "1.0.1"
paging = "3.3.2"
lottie = "6.4.0"
fcm = "24.0.1"
dynamicLinks = "21.1.0"
analytics = "22.1.0"
firebaseCrashlyticsPlugin = "3.0.2"
mockk = "1.13.7"
mockito = "5.12.0"

[libraries]
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activityKtx" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-credentials-play-services-auth = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "credentialsPlayServicesAuth" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
mockk = { group ="io.mockk", name = "mockk", version.ref = "mockk"}
mockito = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt-navigation = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigation" }
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
android-tools-common = { group = "com.android.tools", name = "common", version.ref = "androidTools" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
androidx-material = { group = "androidx.compose.material", name = "material" }
androidx-material-icons = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }
javax-inject = { module = "javax.inject:javax.inject", version.ref = "javaxInject" }
desugaring = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugaring" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttp-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
retrofit-core = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-gson-converter = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization"}
glide = { group = "com.github.bumptech.glide", name = "compose", version.ref = "glide" }
calendar-compose = { group = "com.kizitonwose.calendar", name = "compose", version.ref = "calendar" }
googleid = { group = "com.google.android.libraries.identity.googleid", name = "googleid", version.ref = "googleid" }
jsoup = { group ="org.jsoup", name ="jsoup", version.ref = "jsoup"}
androidx-webkit = { group = "androidx.webkit", name = "webkit", version.ref = "webkit" }
lottie = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottie"}
gms-play-services-auth = { group = "com.google.android.gms", name = "play-services-auth", version.ref = "playServicesAuth"}
kotlinx-coroutines-play-services = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-play-services", version.ref="playServicesCoroutines"}
androidx-datastore = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "androidxDataStore" }
androidx-datastore-core = { group = "androidx.datastore", name = "datastore-preferences-core", version.ref = "androidxDataStore" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
paging-runtime = { group = "androidx.paging", name = "paging-runtime", version.ref = "paging" }
paging-common = { group = "androidx.paging", name = "paging-common", version.ref = "paging" }
paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "paging" }
firebase-cloud-messaging = { group = "com.google.firebase", name = "firebase-messaging-ktx", version.ref = "fcm" }
firebase-dynamic-links = { group = "com.google.firebase", name = "firebase-dynamic-links-ktx", version.ref = "dynamicLinks" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics-ktx", version.ref = "analytics" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics-ktx" }
kakao-v2-user = { group = "com.kakao.sdk", name = "v2-user", version = "2.10.0" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlyticsPlugin" }
gms = { id = "com.google.gms.google-services", version.ref = "gmsPlugin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin"}

noffice-android-application = { id = "noffice.android.application", version = "unspecified" }
noffice-android-application-compose = { id = "noffice.android.application.compose", version = "unspecified" }
noffice-android-application-firebase = { id = "noffice.android.application.firebase", version = "unspecified" }
noffice-android-application-flavors = { id = "noffice.android.application.flavors", version = "unspecified" }
noffice-android-application-test = { id="noffice.android.application.test", version="unspecified" }
noffice-android-feature = { id = "noffice.android.feature", version = "unspecified" }
noffice-android-hilt = { id = "noffice.android.hilt", version = "unspecified" }
noffice-android-library = { id = "noffice.android.library", version = "unspecified" }
noffice-android-library-compose = { id = "noffice.android.library.compose", version = "unspecified" }
noffice-jvm-library = { id = "noffice.jvm.library", version = "unspecified" }